server:
  port: 8081

spring:
  application:
    name: cloud-terminal

  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ztna-realm

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:ztna_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kubernetes:
  config:
    master-url: ""
    namespace: ztna-terminals
    token: ""
